// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package tutorial

import (
	"time"
)

type Payment struct {
	PaymentID   int32
	CustomerID  int32
	StaffID     int32
	RentalID    int32
	Amount      string
	PaymentDate time.Time
}
